### ISSUE TITLE
Magit - can't read current line

### ISSUE THREAD

**Issue by sebasmonia** [MaxSt/challenger-deep#12]
When looking at a finer diff in Magit, if I highlight a line the detail on it is lost.
See below the `}` dissappear...

![image](https://user-images.githubusercontent.com/1651857/67812294-73eb8800-fa64-11e9-9a8c-59124a88588c.png)

Cursor on red line:

![image](https://user-images.githubusercontent.com/1651857/67812304-7cdc5980-fa64-11e9-92dc-c2f6b12f128a.png)

Cursor on green line:

![image](https://user-images.githubusercontent.com/1651857/67812319-88c81b80-fa64-11e9-910e-9d26559a83a1.png)

Tried to change it so that when you are over a diff line it changes the forerground to white, but ended with all Magit diff lines as white. So, not sure how to correct it.

**Comment by MaxSt** [comment]
Thanks for reporting this! :+1: 
This happens, because of the background color of `hl-line-mode`.
I tried a few things here but was not satisfied with using one of the existing colors for the fg highlight of `magit-diff-removed-highlight` and `magit-diff-added-highlight`, so I came up with the idea to introducing new colors for this:
This will be the normal highlighting, when the cursor is not in a deleted or added line:
![normal](https://user-images.githubusercontent.com/720801/67951836-8ee90400-fbec-11e9-9b0d-ef46e7ea5491.png)
This is how the highlighting would look, when the cursor is on a deleted line:
![over-d](https://user-images.githubusercontent.com/720801/67951861-9c05f300-fbec-11e9-82bb-d308d74c52ae.png)
and this is how the highlighting would look if the cursor is on an added line:
![over-n](https://user-images.githubusercontent.com/720801/67951886-a922e200-fbec-11e9-98b5-fa0fa89decb3.png)

I created a new branch for testing these changes, because I am not entirely sure about them and also want to wait for your feedback on this. I added the changes to this branch: https://github.com/challenger-deep-theme/emacs/tree/magit-hl

What do you think about the proposed changes?

**Comment by sebasmonia** [comment]
I like it. It's not that common of a scenario anyway, once in a blue moon I want to pick up a single change from the line to yank somewhere else.

Thank you!!!

**Comment by MaxSt** [comment]
:+1: Merged https://github.com/challenger-deep-theme/emacs/pull/13
